version: '3.8'

services:
  bananint:
    build: .
    container_name: bananint-app
    ports:
      - "3000:80" # Maps port 80 in container to port 3000 on host
    restart: always
    environment:
      - NODE_ENV=production
